#!/bin/bash

clear
python3 app/frontend/logo.py

media_dir="/home/public/media/post_tracker"
# sudo chown -cR user "$media_dir"

if ! [ -d "$media_dir" ]; then
    echo "Making Directory $media_dir"
    mkdir -p "$media_dir"
fi

echo "STARTING POST TRACKER SCRIPT ..."
sleep 1

python3 app/core/manage.py runserver

