# Generated by Django 5.1.2 on 2024-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='شماره سفارش')),
                ('tracking_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='کد رهگیری')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تماس')),
                ('customer', models.CharField(max_length=65, verbose_name='نام کامل مشتری')),
                ('image', models.ImageField(upload_to='screen_shots/', verbose_name='اسکرین شات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری اسکرین شات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به روزرسانی')),
            ],
        ),
    ]
