# Generated by Django 5.1.2 on 2024-10-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='customer',
            field=models.CharField(blank=True, max_length=65, verbose_name='نام کامل مشتری'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(blank=True, upload_to='screen_shots/', verbose_name='اسکرین شات'),
        ),
    ]
