# Generated by Django 5.1.2 on 2024-10-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_screenshot_customer_alter_screenshot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_number', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='کد سفارش')),
                ('tracking_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='کد رهگیری')),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='شماره تماس')),
                ('customer', models.CharField(blank=True, max_length=300, null=True, verbose_name='مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری اسکرین شات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به روزرسانی')),
            ],
            options={
                'verbose_name': 'کد رهگیری',
                'verbose_name_plural': 'کد های رهگیری',
            },
        ),
        migrations.CreateModel(
            name='RequestCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='کد سفارش')),
                ('customer', models.CharField(blank=True, max_length=300, null=True, verbose_name='مشتری')),
                ('status', models.CharField(blank=True, max_length=300, null=True, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری اسکرین شات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به روزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری درخواست دهنده',
                'verbose_name_plural': 'مشتری های درخواست دهنده',
            },
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'verbose_name': 'اسکرین شات', 'verbose_name_plural': 'اسکرین شات ها'},
        ),
    ]
